apiVersion: apps/v1
kind: Deployment
metadata:
  name: deep-user-inquiry
  labels:
    app.kubernetes.io/name: deep-user-inquiry
    app.kubernetes.io/instance: deep-user-inquiry
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: deep-user-inquiry
      app.kubernetes.io/instance: deep-user-inquiry
  template:
    metadata:
      labels:
        app.kubernetes.io/name: deep-user-inquiry
        app.kubernetes.io/instance: deep-user-inquiry
    spec:
      containers:
        - name: deep-user-inquiry
          image: asia.gcr.io/poc-innovation-iot/deep-user-inquiry:TAG
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: deep-user-inquiry-secret-env
          volumeMounts:
              - mountPath: /config/config.yaml
                name: deep-user-inquiry-configmap-file
                subPath: config.yaml
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            timeoutSeconds: 10
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            timeoutSeconds: 10
            initialDelaySeconds: 10
          resources:
            limits:
              cpu: 600m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 128Mi
      volumes:
        - name: deep-user-inquiry-secret-file
          secret:
            secretName: deep-user-inquiry-secret-file
        - name: deep-user-inquiry-configmap-file
          configMap:
            name: deep-user-inquiry-configmap-file